### main  page
GET http://localhost:3000/

### get all funds
GET http://localhost:3000/api/funds


### get one
GET http://localhost:3000/api/funds/1

### create single
POST http://localhost:3000/api/funds
Content-Type: application/json

{
  "author_name": "Jake",
  "idea_name": "Save trees",
  "description": "Save trees. Be green. Donate. Breath.",
  "rise_funds": "10000",
  "img_url": "https://picsum.photos/id/43/800/600"
}

### donate single
POST http://localhost:3000/api/funds/donated
Content-Type: application/json

{
  "name": "Jake",
  "donated_sum": 20,
  "idea_id": "",
}

### update idea
PUT http://localhost:3000/api/funds/7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamFuZUBiaXQubHQiLCJzY29wZSI6Im1hbmFnZXIifSwiaWF0IjoxNzA4NDMwNjk2LCJleHAiOjE3MDg0MzQyOTZ9.xVyrJRhDLAxWLL3_onopirPqvshdF2BvD53yJEOawBs

{
  "author_name": "Jane",
  "idea_name": "Donate me for my course",
  "description": "Please donate for my JavaScript course",
  "rise_funds": "2500",
  "img_url": "https://picsum.photos/id/223/800/600",
  "admin_comnfirmation": 0
}

### delete single idea
DELETE http://localhost:3000/api/funds/15
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiamFuZUBiaXQubHQiLCJzY29wZSI6Im1hbmFnZXIifSwiaWF0IjoxNzA4NDMwNjk2LCJleHAiOjE3MDg0MzQyOTZ9.xVyrJRhDLAxWLL3_onopirPqvshdF2BvD53yJEOawBs

### Registration
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Jane",
  "email": "jane@bit.lt",
  "password": "123456"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jane@bit.lt",
  "password": "123456"
}